
name: Pipeline para Deploy da aplicação

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Compilação
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Compilar projeto
        run: mvn clean package -DskipTests
        working-directory: api-clientes

      - name: Pegar os arquivos da pasta target
        run: ls -la target

      - name: Gerando o arquivo JAR compilado do projeto
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar

  test:
    name: Testes
    runs-on: ubuntu-22.04
    needs: build
    steps:
       - name: Checkout do código
         uses: actions/checkout@v2

       - name: Configuração do JDK 21
         uses: actions/setup-java@v2
         with:
            java-version: "17"
            distribution: "temurin"

       - name: Rodar testes com cobertura JaCoCo
         run: mvn clean test

       - name: Upload dos relatórios de testes (Surefire)
         uses: actions/upload-artifact@v4
         with:
           name: surefire-reports
           path: target/surefire-reports/

       - name: Upload dos relatórios de cobertura (JaCoCo)
         uses: actions/upload-artifact@v4
         with:
            name: jacoco-report
            path: target/site/jacoco/

  deploy:
    name: Publicação
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


